export { default as MasterPage } from './MasterPage'
export { default as UserMenu } from './UserMenu'
export { default as SearchBar } from './SearchBar'
export { default as MovieCard } from './MovieCard'
export { default as Footer } from './Footer'
export { default as MoviesList } from './MoviesList'
